### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by goranGG** [Sarl-EDPS/OctoberCms-Push#1]
hi

images in documentation are broken and not loading

**Comment by jimibi** [comment]
Hi,
I just realized that the service(ctrlv.in) I was using to store my images has just closed.
As soon as I get back to the office I will store them on my personal server.
Thank you for letting me know.

**Comment by goranGG** [comment]
no problem, it would be great to make a video for setup one application, there are some arrows on settings not sure what are these for, just to make it easier to setup plugin
